In [1]:
import numpy as np
import pandas as pd
from sklearn import svm
from sklearn.metrics import accuracy_score

c:\users\shi-rui\appdata\local\programs\python\python37\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
c:\users\shi-rui\appdata\local\programs\python\python37\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
c:\users\shi-rui\appdata\local\programs\python\python37\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [3]:
dataroot = 'watermelon.csv'
df = pd.read_csv(dataroot)

In [4]:
samples = np.zeros((17, 8))
labels = np.zeros((17, 1))

feature1 = {'青绿': 1, '乌黑': 2, '浅白': 3}
feature2 = {'蜷缩': 1, '稍蜷': 2, '硬挺': 3}
feature3 = {'浊响': 1, '沉闷': 2, '清脆': 3}
feature4 = {'清晰': 1, '稍糊': 2, '模糊': 3}
feature5 = {'凹陷': 1, '稍凹': 2, '平坦': 3}
feature6 = {'硬滑': 1, '软粘': 2}

for row in range(df.shape[0]):
    samples[row][0] = feature1[df.iloc[row][1]]
    samples[row][1] = feature2[df.iloc[row][2]]
    samples[row][2] = feature3[df.iloc[row][3]]
    samples[row][3] = feature4[df.iloc[row][4]]
    samples[row][4] = feature5[df.iloc[row][5]]
    samples[row][5] = feature6[df.iloc[row][6]]
    samples[row][6] = df.iloc[row][7]
    samples[row][7] = df.iloc[row][8]
    labels[row][0] = 1 if df.iloc[row][9] == '是' else -1
    

labels = np.reshape(labels, -1)
flag = np.array([0, 0, 0, 0, 0, 0, 1, 1])

In [17]:
idx = list(range(17))
np.random.shuffle(idx)

training_idx = idx[:14]
training_samples = samples[training_idx]
training_labels = labels[training_idx]

testing_idx = idx[14:]
testing_samples = samples[testing_idx]
testing_labels = labels[testing_idx]

**poly kernel**

In [33]:
clf = svm.SVC(kernel='poly', C=0.1, degree=3)
clf.fit(training_samples, training_labels)
pred_labels = clf.predict(testing_samples)
print(testing_labels, pred_labels)
print('ACC score: {}'.format(accuracy_score(testing_labels, pred_labels)))

[ 1.  1. -1.] [ 1.  1. -1.]
ACC score: 1.0


**linear kernel**

In [32]:
clf = svm.SVC(kernel='linear', C=0.1)
clf.fit(training_samples, training_labels)
pred_labels = clf.predict(testing_samples)
print(testing_labels, pred_labels)
print('ACC score: {}'.format(accuracy_score(testing_labels, pred_labels)))

[ 1.  1. -1.] [ 1.  1. -1.]
ACC score: 1.0


**rbf kernel**

In [30]:
clf = svm.SVC(kernel='rbf')
clf.fit(training_samples, training_labels)
pred_labels = clf.predict(testing_samples)
print(testing_labels, pred_labels)
print('ACC score: {}'.format(accuracy_score(testing_labels, pred_labels)))

[ 1.  1. -1.] [ 1.  1. -1.]
ACC score: 1.0


**sigmoid kernel**

In [31]:
clf = svm.SVC(kernel='sigmoid')
clf.fit(training_samples, training_labels)
pred_labels = clf.predict(testing_samples)
print(testing_labels, pred_labels)
print('ACC score: {}'.format(accuracy_score(testing_labels, pred_labels)))

[ 1.  1. -1.] [-1. -1. -1.]
ACC score: 0.3333333333333333
